### ISSUE TITLE
Concurrent map write

### ISSUE THREAD

**Issue by gazhayes** [fiatjaf/go-nostr#12]
Probably needs a mutex here.
@fiatjaf if you fix it cool, if not and it keeps bugging me I'll eventually send you a pull request.

```
fatal error: concurrent map read and map write

goroutine 125 [running]:
runtime.throw({0x14d0672?, 0xc000225108?})
	/usr/local/Cellar/go/1.18/libexec/src/runtime/panic.go:992 +0x71 fp=0xc001021d40 sp=0xc001021d10 pc=0x1033f91
runtime.mapaccess2_faststr(0xc0010481d0?, 0x10?, {0xc0010481f0, 0xe})
	/usr/local/Cellar/go/1.18/libexec/src/runtime/map_faststr.go:117 +0x3d4 fp=0xc001021da8 sp=0xc001021d40 pc=0x1013cd4
github.com/fiatjaf/go-nostr.(*RelayPool).Add.func1()
	/Users/gareth/go/pkg/mod/github.com/fiatjaf/go-nostr@v0.7.4/relaypool.go:155 +0x217 fp=0xc001021fe0 sp=0xc001021da8 pc=0x12a6e77
runtime.goexit()
	/usr/local/Cellar/go/1.18/libexec/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc001021fe8 sp=0xc001021fe0 pc=0x1063d81
created by github.com/fiatjaf/go-nostr.(*RelayPool).Add
	/Users/gareth/go/pkg/mod/github.com/fiatjaf/go-nostr@v0.7.4/relaypool.go:111 +0x445
```

**Comment by fiatjaf** [comment]
I thought open-source was this magical world in which other programmers would fix our bugs and instead all I got was this lousy issue.
